### PR TITLE
Fixing not being able to install on Laravel 7

### PR DESCRIPTION
**Pull request by CWDN**
## Description

Updating the symfony process version and fixing any related breaking changes. 

## Motivation and context

Tried to install this on a Laravel 7 project and couldn't because the symfony process version was too low (4.* and Laravel 7 requires 5.*).

## How has this been tested?

Used the phpunit tests you've already written to prove the upgrade was successful.

## Types of changes

What types of changes does your code introduce? Put an `x` in all the boxes that apply:
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

Go over all the following points, and put an `x` in all the boxes that apply.

Please, please, please, don't send your pull request until all of the boxes are ticked. Once your pull request is created, it will trigger a build on our [continuous integration](http://www.phptherightway.com/#continuous-integration) server to make sure your [tests and code style pass](https://help.github.com/articles/about-required-status-checks/).

- [x] I have read the **[CONTRIBUTING](CONTRIBUTING.md)** document.
- [x] My pull request addresses exactly one patch/feature.
- [x] I have created a branch for this patch/feature.
- [x] Each individual commit in the pull request is meaningful.
- [x] I have added tests to cover my changes.
  - Didn't add any extra tests as the current suite was sufficient to prove everything was working as expected.
- [x] If my change requires a change to the documentation, I have updated it accordingly.

If you're unsure about any of these, don't hesitate to ask. We're here to help!

### CODE REVIEW

**Comment by slavarazum** [comment]
Thanks for PR 👍 Will take a look, why tests has been passed.

**Comment by slavarazum** [comment]
Also minimum `symfony/process` version must be upper than 4.1. Because `Process::fromShellCommandline` method doesn't exists in 4.1

**Comment by CWDN** [comment]
Ah good spot, sorry about that, Thanks for merging.

**Comment by slavarazum** [comment]
Just republished 3.0 version, enjoy

**Pull request merged**
