### PR TITLE
Fixed errors message.

### PR DESCRIPTION
**Pull request by dima-bzz**
Signed-off-by: Dmitry Mazurov <dimabzz@gmail.com>

## Description

Fixed errors message.

## Motivation and context

These changes fix the error if after installation they did not execute config: cache. It also corrects an error if getErrorOutput is empty, but there is an error.

## How has this been tested?

Please describe in detail how you tested your changes.

Include details of your testing environment, and the tests you ran to
see how your change affects other areas of the code, etc.

## Screenshots (if appropriate)
Снимок экрана 2020-01-20 в 14 49 55
Снимок экрана 2020-01-20 в 14 45 11

## Types of changes

What types of changes does your code introduce? Put an `x` in all the boxes that apply:
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

Go over all the following points, and put an `x` in all the boxes that apply.

Please, please, please, don't send your pull request until all of the boxes are ticked. Once your pull request is created, it will trigger a build on our [continuous integration](http://www.phptherightway.com/#continuous-integration) server to make sure your [tests and code style pass](https://help.github.com/articles/about-required-status-checks/).

- [x] I have read the **[CONTRIBUTING](CONTRIBUTING.md)** document.
- [x] My pull request addresses exactly one patch/feature.
- [x] I have created a branch for this patch/feature.
- [x] Each individual commit in the pull request is meaningful.
- [x] I have added tests to cover my changes.
- [x] If my change requires a change to the documentation, I have updated it accordingly.

If you're unsure about any of these, don't hesitate to ask. We're here to help!

### CODE REVIEW

**Comment by slavarazum** [comment]
Hi, thanks for contributing.

Don't see any test cases and could you please explain this:

> These changes fix the error if after installation they did not execute config: cache

in more details.

**Comment by dima-bzz** [comment]
@slavarazum If the `bootstrap/cache/config.php` file exists before installation, the config will be read from this file. If after installation they did not execute config: cache, then the $ env variable will be an array, because it will not be able to find the `initializer.env_config_key` config, which entails a performance error.

**Comment by slavarazum** [comment]
Don't see any reasons for having cached configuration options, before application has been installed.

**Comment by dima-bzz** [comment]
@slavarazum Yes, I forgot to say that this manifests itself mainly during development, since the package is already put into the working environment. If the config is cached during development, there will be such an error.

**Comment by slavarazum** [comment]
It's conceptual issue. `app:install` should be run on fresh repository clone, no sense to run it after initial setup.

**Comment by dima-bzz** [comment]
@slavarazum I agree. But the second problem is that the message is empty.

**Comment by slavarazum** [comment]
Feel free to resubmit PR with appropriate fix and testcases.

**Pull request closed without merging**
